package VolumenApp;

/**
* VolumenApp/VolumenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Volumen.idl
* viernes 14 de noviembre de 2014 03:55:25 PM PET
*/

public final class VolumenHolder implements org.omg.CORBA.portable.Streamable
{
  public VolumenApp.Volumen value = null;

  public VolumenHolder ()
  {
  }

  public VolumenHolder (VolumenApp.Volumen initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VolumenApp.VolumenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VolumenApp.VolumenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VolumenApp.VolumenHelper.type ();
  }

}
