package VolumenApp;


/**
* VolumenApp/VolumenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Volumen.idl
* viernes 14 de noviembre de 2014 03:55:25 PM PET
*/

public interface VolumenOperations 
{
  double volumen (double radio);
  void shutdown ();
} // interface VolumenOperations
